# Generated by Django 5.0.1 on 2024-01-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinalert',
            name='coin_symbol',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinalert',
            name='threshold_price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinalert',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coin_alert_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
