# Generated by Django 5.0.1 on 2024-01-03 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_coinalert_coin_symbol_coinalert_threshold_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinalert',
            name='coin_symbol',
        ),
        migrations.CreateModel(
            name='CoinSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coin_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_alert', to='tracker.coinalert')),
            ],
        ),
    ]
