# Generated by Django 5.0.1 on 2024-01-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_coinalert_coin_symbol_coinsymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsymbol',
            name='coin_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_alert', to='tracker.coinalert'),
        ),
    ]
