# Generated by Django 5.0.1 on 2024-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_coinsymbol_coin_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsymbol',
            name='kafka_topic',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
