# Generated by Django 5.0.1 on 2024-01-03 14:04

from django.db import migrations

from django.db import migrations, transaction


def populate_coinsymbols(apps, schema_editor):
    
    CoinSymbol = apps.get_model("tracker", "CoinSymbol")
    CoinSymbol.objects.all().delete()
    coins = [
        "btc",
        "eth",
        "bnb",
        "sol",
        "xrp",
        "usdc",
        "ada",
        "avax",
        "doge",
        "dot",
        "trx",
        "matic",
        "link",
        "wbtc",
        "icp",
        "shib",
        "dai",
        "ltc",
        "bch",
        "uni",
        "atom",
        "near",
        "xlm",
        "op",
        "fil",
        "hbar",
        "xmr",
        "etc",
    ]
    with transaction.atomic():
        for coin in coins:
            CoinSymbol.objects.create(symbol=coin, kafka_topic=f"{coin}-topic")

def delete_coinsymbols(apps, schema_editor):
    CoinSymbol = apps.get_model("tracker", "CoinSymbol")
    CoinSymbol.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_coinsymbol_kafka_topic'),
    ]

    operations = [
        migrations.RunPython(populate_coinsymbols, delete_coinsymbols),
    ]
