# Generated by Django 5.0.1 on 2024-01-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20240103_2014'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION notify_event() RETURNS TRIGGER AS $$
            DECLARE
            BEGIN
                PERFORM pg_notify('tracker_coinsymbol', NEW.kafka_topic::text);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER tracker_coinsymbol_trigger
            AFTER INSERT ON tracker_coinsymbol
            FOR EACH ROW EXECUTE PROCEDURE notify_event();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS tracker_coinsymbol_trigger ON tracker_coinsymbol;
            DROP FUNCTION IF EXISTS notify_event();
            """
        ),
    ]
