# Generated by Django 5.0.1 on 2024-01-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20240104_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinsymbol',
            name='coin_alert',
        ),
        migrations.AddField(
            model_name='coinalert',
            name='coin_symbol',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='coin_symbol', to='tracker.coinsymbol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinalert',
            name='status',
            field=models.CharField(choices=[('untriggered', 'UNTRIGGERED'), ('triggered', 'TRIGGERED'), ('mail_sent', 'MAIL_SENT')], default='untriggered', max_length=20),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
