# Generated by Django 5.0.1 on 2024-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_coinsymbol_coin_alert_coinalert_coin_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinalert',
            name='delta',
            field=models.CharField(choices=[('above', 'ABOVE'), ('below', 'BELOW')], default='above', max_length=10),
            preserve_default=False,
        ),
    ]
