# Generated by Django 5.0.1 on 2024-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_coinalert_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinalert',
            name='delta',
        ),
        migrations.AddField(
            model_name='coinalert',
            name='buy_or_sell',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default='buy', max_length=20),
            preserve_default=False,
        ),
    ]
